-- The location archive: raw sources, resolved places, and the views that turn one into the
-- other. Safe to run twice.
--
-- The shape follows from one decision: a position log is not the history. A history is
-- *stays* (you were here, from then until then) and *journeys* (you went from here to there,
-- this way, this far). Google's export already carries both, inferred with sensors no
-- reverse-geocoder can replace, so importing it into one flat coordinate table would throw
-- away the only part worth having. Each shape therefore keeps its own table, and
-- `location_v_stays` is the single spine everything reads.

begin;

-- --------------------------------------------------------------------- resolved places

-- One row per distinct spot, geocoded once and reused forever. Every other table points here
-- rather than carrying its own copy of an address, so re-geocoding one place fixes it
-- everywhere at once.
create table if not exists location_places (
  id            bigint generated by default as identity primary key,
  lat           double precision not null,
  lon           double precision not null,
  address       text,
  label         text,
  city          text,
  admin         text,
  country       text,
  country_code  text,
  tz            text,
  created_at    timestamptz not null default now()
);
create index if not exists location_places_lat_lon_idx on location_places (lat, lon);
create index if not exists location_places_country_idx on location_places (country_code);

-- --------------------------------------------------------------------------- live pings

-- What a phone reports while you carry it: OwnTracks, a shortcut, an imported point. The
-- place_id is filled in later by the geocoder, because Nominatim allows one call per second
-- and an import arrives with thousands of new spots.
create table if not exists location_pings (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  captured_at  timestamptz,
  lat          double precision not null,
  lon          double precision not null,
  accuracy_m   double precision,
  label        text,
  tz           text,
  local_time   text,
  source       text,
  token        text,
  place_id     bigint references location_places (id),
  resolved_at  timestamptz
);
create index if not exists location_pings_captured_at_idx on location_pings (captured_at desc);
create index if not exists location_pings_created_at_idx on location_pings (created_at desc);
create index if not exists location_pings_place_idx on location_pings (place_id);
-- Partial, because the enricher's only query is "which ones still have no place", and that
-- set shrinks to nothing while the table grows forever.
create index if not exists location_pings_unresolved_idx on location_pings (id) where place_id is null;
-- Re-importing the same export is the normal case, not the exception: a phone re-exports its
-- whole history every time. A natural key per source lets every insert be a no-op the second
-- time round.
create unique index if not exists location_pings_import_key
  on location_pings (source, captured_at, lat, lon) where source like 'gtl:%';

-- Bearer tokens for the HTTP ingest endpoint. One row per device, so a phone can be revoked
-- without touching the others.
create table if not exists location_auth (
  token       text primary key,
  label       text,
  created_at  timestamptz not null default now()
);

-- ------------------------------------------------------------------------ google export

-- A stay, as Google measured it: a start, an end, and its own guess at what kind of place it
-- is. Durations are read from here rather than modelled, which is the whole reason to import
-- it instead of interpolating between fixes.
create table if not exists location_visits (
  id               bigint generated by default as identity primary key,
  started_at       timestamptz not null,
  ended_at         timestamptz not null,
  start_offset_m   integer,
  end_offset_m     integer,
  google_place_id  text,
  lat              double precision not null,
  lon              double precision not null,
  semantic_type    text,
  probability      real,
  hierarchy_level  integer,
  place_id         bigint references location_places (id),
  source           text,
  unique (started_at, ended_at, lat, lon)
);
create index if not exists location_visits_time_idx on location_visits (started_at);
create index if not exists location_visits_place_idx on location_visits (place_id);
create index if not exists location_visits_gplace_idx on location_visits (google_place_id);
create index if not exists location_visits_source_idx on location_visits (source) where source is not null;

-- A journey between two stays, with the transport mode the phone's sensors inferred and
-- Google's own distance. Nothing here can be recomputed from coordinates: the mode is a
-- sensor fusion result, and the distance follows the route rather than the straight line.
create table if not exists location_activities (
  id              bigint generated by default as identity primary key,
  started_at      timestamptz not null,
  ended_at        timestamptz not null,
  start_offset_m  integer,
  end_offset_m    integer,
  mode            text,
  probability     real,
  distance_m      double precision,
  start_lat       double precision not null,
  start_lon       double precision not null,
  end_lat         double precision not null,
  end_lon         double precision not null,
  start_place_id  bigint references location_places (id),
  end_place_id    bigint references location_places (id),
  source          text,
  unique (started_at, ended_at, start_lat, start_lon, end_lat, end_lon)
);
create index if not exists location_activities_time_idx on location_activities (started_at);
create index if not exists location_activities_mode_idx on location_activities (mode);
create index if not exists location_activities_source_idx on location_activities (source) where source is not null;

-- Google's own place identity, which survives across exports even when the coordinates move
-- by a few metres. Its profile label is how "HOME" is known, and home is what every
-- km-from-home number is measured against.
create table if not exists location_google_places (
  place_id       text primary key,
  lat            double precision not null,
  lon            double precision not null,
  profile_label  text,
  place_id_ref   bigint references location_places (id),
  first_seen     timestamptz,
  last_seen      timestamptz,
  visit_count    integer not null default 0,
  total_seconds  bigint not null default 0
);

-- The raw fix log: the only place altitude and speed exist. Kept separate because it is an
-- order of magnitude bigger than everything else and nothing else needs to read it.
create table if not exists location_raw_positions (
  id           bigint generated by default as identity primary key,
  captured_at  timestamptz not null,
  lat          double precision not null,
  lon          double precision not null,
  accuracy_m   real,
  altitude_m   real,
  speed_ms     real,
  source       text,
  unique (captured_at, lat, lon)
);
create index if not exists location_raw_time_idx on location_raw_positions (captured_at);

-- Route geometry, kept so a day can be drawn rather than only listed.
create table if not exists location_path_points (
  id           bigint generated by default as identity primary key,
  captured_at  timestamptz not null,
  lat          double precision not null,
  lon          double precision not null,
  unique (captured_at, lat, lon)
);
create index if not exists location_path_time_idx on location_path_points (captured_at);

-- What the phone's sensors thought you were doing, with every candidate and its confidence.
create table if not exists location_activity_records (
  id           bigint generated by default as identity primary key,
  captured_at  timestamptz not null unique,
  top_type     text,
  top_conf     real,
  candidates   jsonb not null default '[]'::jsonb
);
create index if not exists location_actrec_time_idx on location_activity_records (captured_at);

-- Trips Google detected on its own, kept next to the ones detected here so the two can be
-- compared rather than one silently overwriting the other.
create table if not exists location_memories (
  id              bigint generated by default as identity primary key,
  started_at      timestamptz not null,
  ended_at        timestamptz not null,
  start_offset_m  integer,
  end_offset_m    integer,
  distance_km     double precision,
  destinations    jsonb not null default '[]'::jsonb,
  unique (started_at, ended_at)
);

create table if not exists location_wifi_scans (
  id            bigint generated by default as identity primary key,
  captured_at   timestamptz not null unique,
  device_count  integer not null default 0,
  devices       jsonb not null default '[]'::jsonb
);
create index if not exists location_wifi_time_idx on location_wifi_scans (captured_at);

create table if not exists location_profile (
  id               integer primary key default 1,
  updated_at       timestamptz not null default now(),
  frequent_places  jsonb not null default '[]'::jsonb,
  frequent_trips   jsonb not null default '[]'::jsonb
);

-- One row per imported file, keyed by content hash, so the import history is itself readable
-- and the same file twice is a no-op you can see rather than infer.
create table if not exists location_imports (
  id           bigint generated by default as identity primary key,
  imported_at  timestamptz not null default now(),
  file_sha256  text not null unique,
  file_bytes   bigint,
  span_start   timestamptz,
  span_end     timestamptz,
  counts       jsonb not null default '{}'::jsonb
);

-- ------------------------------------------------------------------------------- trips

create table if not exists location_trips (
  id                bigint generated by default as identity primary key,
  slug              text not null unique,
  name              text not null,
  note              text not null default '',
  started_at        timestamptz not null,
  ended_at          timestamptz not null,
  nights            integer not null default 0,
  countries         text[] not null default '{}',
  country_codes     text[] not null default '{}',
  cities            text[] not null default '{}',
  primary_country   text,
  distance_km       double precision,
  max_km_from_home  double precision,
  cover_place_id    bigint references location_places (id),
  -- A name you typed yourself is never overwritten by the detector. Without this flag, every
  -- re-run silently renames "Honeymoon" back to "Italy — June 2025".
  name_is_auto      boolean not null default true,
  detected_at       timestamptz not null default now(),
  created_at        timestamptz not null default now()
);
create index if not exists location_trips_window on location_trips (started_at, ended_at);

-- --------------------------------------------------------------------------- functions

create or replace function location_km(lat0 double precision, lon0 double precision,
                                       lat1 double precision, lon1 double precision)
returns double precision
language sql immutable parallel safe
set search_path to 'public', 'pg_temp'
as $$
  select case
    when lat0 is null or lon0 is null or lat1 is null or lon1 is null then null
    else 6371.0 * 2 * asin(least(1.0, sqrt(
      sin(radians(lat1 - lat0) / 2) ^ 2
      + cos(radians(lat0)) * cos(radians(lat1)) * sin(radians(lon1 - lon0) / 2) ^ 2)))
  end
$$;

-- ---------------------------------------------------------------------------- the spine

-- Every stay, from both sources, as one stream.
--
-- Visits are authoritative wherever they exist, and the live ping tail only covers what comes
-- after the last one. Without that cut the two sources double-count the overlap, and a day
-- present in both reads as two separate stays in the same place.
create or replace view location_v_stays as
with cut as (
  select coalesce(max(ended_at), '-infinity'::timestamptz) as t from location_visits
), visited as (
  select 'visit'::text as source, v.started_at, v.ended_at,
         coalesce(v.start_offset_m, 0) as off_m,
         extract(epoch from v.ended_at - v.started_at)::bigint as seconds,
         v.place_id, v.semantic_type, v.lat, v.lon, 1::bigint as fixes
  from location_visits v
  where v.place_id is not null
), tail_marked as (
  select p.captured_at, p.place_id, p.lat, p.lon,
         (p.place_id is distinct from lag(p.place_id) over (order by p.captured_at))::int as brk
  from location_pings p cross join cut c
  where p.place_id is not null and coalesce(p.captured_at, p.created_at) > c.t
), tail_run as (
  select tail_marked.*,
         sum(brk) over (order by captured_at rows unbounded preceding) as run
  from tail_marked
), tailed as (
  select 'ping'::text as source, min(captured_at) as started_at, max(captured_at) as ended_at,
         0 as off_m,
         -- A phone that goes quiet for a week did not stand still for a week. Capping the run
         -- at 72 hours keeps one flat battery from reading as the longest stay on record.
         least(extract(epoch from max(captured_at) - min(captured_at)),
               (72 * 3600)::numeric)::bigint as seconds,
         place_id, null::text as semantic_type, avg(lat) as lat, avg(lon) as lon,
         count(*) as fixes
  from tail_run group by run, place_id
), joined as (
  select s.source, s.started_at, s.ended_at, s.seconds, s.semantic_type, s.fixes, s.lat, s.lon,
         case when s.source = 'visit' then s.off_m
              else (extract(epoch from (s.started_at at time zone coalesce(nullif(pl.tz, ''), 'UTC'))
                                     - (s.started_at at time zone 'UTC')) / 60)::int end as off_m,
         pl.id as place_id, pl.label, pl.address, pl.city, pl.admin, pl.country,
         pl.country_code, pl.tz
  from (select * from visited union all select * from tailed) s
  join location_places pl on pl.id = s.place_id
)
select j.*,
       -- The local date, not the UTC one. A stay that starts at 23:00 in Bangkok belongs to
       -- that day, not to the next one because UTC had already turned over.
       (j.started_at + make_interval(mins => j.off_m))::date as day,
       t.id as trip_id, t.slug as trip_slug, t.name as trip_name
from joined j
left join location_trips t on j.started_at >= t.started_at and j.started_at < t.ended_at;

-- One row per calendar day, with the place you spent the most time in as its anchor.
create or replace view location_v_days as
with visit_days as (
  select generate_series(
           (v.started_at at time zone coalesce(nullif(pl.tz, ''), 'UTC'))::date::timestamptz,
           (v.ended_at   at time zone coalesce(nullif(pl.tz, ''), 'UTC'))::date::timestamptz,
           '1 day'::interval)::date as day,
         pl.id as place_id, pl.city, pl.country, pl.country_code, pl.lat, pl.lon,
         extract(epoch from v.ended_at - v.started_at)::float8 as seconds,
         'visit'::text as origin
  from location_visits v join location_places pl on pl.id = v.place_id
), ping_days as (
  select (p.captured_at at time zone coalesce(nullif(p.tz, ''), nullif(pl.tz, ''), 'UTC'))::date as day,
         pl.id, pl.city, pl.country, pl.country_code, pl.lat, pl.lon,
         0::float8, 'ping'::text
  from location_pings p join location_places pl on pl.id = p.place_id
), all_days as (
  select * from visit_days union all select * from ping_days
), ranked as (
  select all_days.*,
         row_number() over (partition by day order by seconds desc, origin, place_id) as rn
  from all_days
)
select day,
       max(place_id)    filter (where rn = 1) as anchor_place_id,
       max(city)        filter (where rn = 1) as anchor_city,
       max(country)     filter (where rn = 1) as anchor_country,
       max(country_code) filter (where rn = 1) as anchor_country_code,
       max(lat)         filter (where rn = 1) as anchor_lat,
       max(lon)         filter (where rn = 1) as anchor_lon,
       array_agg(distinct country) filter (where country is not null and country <> '') as countries,
       array_agg(distinct city)    filter (where city    is not null and city    <> '') as cities,
       count(distinct place_id) as places,
       bool_or(origin = 'visit') as has_visits,
       bool_or(origin = 'ping')  as has_pings
from ranked group by day;

create or replace view location_place_stats as
select p.id as place_id, p.label, p.city, p.country, p.lat, p.lon,
       coalesce(max(g.profile_label), max(t.semantic_type)) as google_label,
       count(distinct g.place_id) as google_place_count,
       coalesce(sum(g.visit_count), 0::bigint) as visits,
       coalesce(sum(g.total_seconds), 0::numeric) as seconds,
       min(g.first_seen) as first_seen, max(g.last_seen) as last_seen
from location_places p
join location_google_places g on g.place_id_ref = p.id
left join lateral (
  select v.semantic_type from location_visits v
  where v.google_place_id = g.place_id and v.semantic_type is not null
    and v.semantic_type <> 'UNKNOWN'
  group by v.semantic_type order by count(*) desc limit 1) t on true
group by p.id, p.label, p.city, p.country, p.lat, p.lon;

-- Home is a timeline, not a point. Anyone who has moved has several, and every
-- "how far from home" answer has to know which one was home at the time.
create or replace view location_v_home_periods as
select place_id, label, city, country, lat, lon, first_seen, last_seen, seconds
from location_place_stats where google_label = 'HOME';

create or replace view location_v_day_home as
select d.day, d.anchor_place_id, d.anchor_city, d.anchor_country, d.anchor_country_code,
       d.anchor_lat, d.anchor_lon, d.countries, d.cities, d.places, d.has_visits, d.has_pings,
       h.place_id as home_place_id, h.city as home_city, h.country as home_country,
       h.lat as home_lat, h.lon as home_lon,
       location_km(h.lat, h.lon, d.anchor_lat, d.anchor_lon) as km_from_home
from location_v_days d
left join lateral (
  select p.* from location_v_home_periods p
  -- The home that was current on that day wins; failing that, the nearest one in time. A
  -- single global "most lived-in address" would put your current city on a day five years
  -- before you moved there, and every distance from it would be wrong.
  order by (d.day::timestamptz >= p.first_seen and d.day::timestamptz <= p.last_seen) desc,
           p.seconds desc,
           least(abs(extract(epoch from d.day::timestamptz - p.first_seen)),
                 abs(extract(epoch from d.day::timestamptz - p.last_seen)))
  limit 1) h on true;

-- Materialized because every trip query, every stat and every record reads it, and it is a
-- pure function of tables that only change on import.
create materialized view if not exists location_m_day_home as select * from location_v_day_home;
create unique index if not exists location_m_day_home_day_idx on location_m_day_home (day);
create index if not exists location_m_day_home_country_idx on location_m_day_home (anchor_country);

create or replace function location_refresh_days() returns void
language plpgsql security definer set search_path to 'public', 'pg_temp'
as $$ begin refresh materialized view location_m_day_home; end; $$;

-- ------------------------------------------------------------------- trips, detected

-- A trip is a run of days spent outside your home country, or more than 100 km from home.
create or replace view location_v_trip_segments as
with flagged as (
  select d.*, (d.anchor_country is distinct from d.home_country
               or coalesce(d.km_from_home, 0) > 100) as away
  from location_m_day_home d
), runs as (
  select flagged.*,
         sum(case when away then 0 else 1 end)
           over (order by day rows between unbounded preceding and current row) as grp
  from flagged
), away as (
  select * from runs where away
), edges as (
  select away.*,
         lag(day)            over (order by day) as prev_day,
         lag(grp)            over (order by day) as prev_grp,
         lag(anchor_country) over (order by day) as prev_country
  from away
), segmented as (
  select edges.*,
         -- A gap of more than a month breaks the run whatever the country says. Without it,
         -- a hole in the archive glues two separate trips to the same country into one.
         sum(case when prev_day is null or (day - prev_day) > 31
                       or grp is distinct from prev_grp
                       or anchor_country is distinct from prev_country
                  then 1 else 0 end)
           over (order by day rows between unbounded preceding and current row) as seg
  from edges
)
select min(grp) as grp, seg, min(day) as d0, max(day) as d1,
       max(day) - min(day) as nights, count(*) as days_with_data,
       max(anchor_country) as primary_country,
       max(anchor_country_code) as primary_country_code,
       max(home_country) as home_country,
       coalesce(nullif(mode() within group (order by anchor_city), ''),
                max(anchor_country)) as primary_city,
       array_agg(distinct anchor_city) filter (where anchor_city is not null and anchor_city <> '') as cities,
       max(km_from_home) as max_km,
       (array_agg(anchor_place_id order by day))[1] as cover
from segmented group by seg;

create or replace function location_detect_trips(min_nights integer default 1)
returns table(inserted integer, updated integer)
language plpgsql security definer set search_path to 'public', 'pg_temp'
as $$
declare
  n_ins integer := 0;
  n_upd integer := 0;
begin
  refresh materialized view location_m_day_home;

  create temporary table _seg on commit drop as
    select s.*,
           case when s.primary_country is distinct from s.home_country
                then s.primary_country else s.primary_city end as headline
    from location_v_trip_segments s
    where s.nights >= min_nights;

  alter table _seg add column slug text, add column auto_name text;
  update _seg set
    auto_name = coalesce(headline, 'Trip') || ' - ' || to_char(d0, 'FMMonth YYYY'),
    slug = lower(regexp_replace(coalesce(headline, 'trip') || '-' || to_char(d0, 'YYYY-MM-DD'),
                                '[^a-zA-Z0-9]+', '-', 'g'));

  with touched as (
    update location_trips tr
    set    started_at       = f.d0::timestamptz,
           ended_at         = (f.d1 + 1)::timestamptz,
           nights           = f.nights,
           countries        = array_remove(array[f.primary_country], null),
           country_codes    = array_remove(array[f.primary_country_code], null),
           cities           = coalesce(f.cities, '{}'),
           primary_country  = f.primary_country,
           max_km_from_home = f.max_km,
           cover_place_id   = coalesce(tr.cover_place_id, f.cover),
           name             = case when tr.name_is_auto then f.auto_name else tr.name end,
           slug             = case
                                when tr.name_is_auto and not exists (
                                  select 1 from location_trips o
                                  where o.slug = f.slug and o.id <> tr.id)
                                then f.slug else tr.slug end,
           detected_at      = now()
    from _seg f
    where tr.started_at < (f.d1 + 2)::timestamptz
      and tr.ended_at   > (f.d0 - 1)::timestamptz
      and tr.primary_country is not distinct from f.primary_country
    returning 1)
  select count(*) into n_upd from touched;

  with fresh as (
    insert into location_trips
      (slug, name, started_at, ended_at, nights, countries, country_codes, cities,
       primary_country, max_km_from_home, cover_place_id, detected_at)
    select f.slug, f.auto_name, f.d0::timestamptz, (f.d1 + 1)::timestamptz, f.nights,
           array_remove(array[f.primary_country], null),
           array_remove(array[f.primary_country_code], null),
           coalesce(f.cities, '{}'),
           f.primary_country, f.max_km, f.cover, now()
    from _seg f
    where not exists (
      select 1 from location_trips e
      where e.started_at < (f.d1 + 2)::timestamptz
        and e.ended_at   > (f.d0 - 1)::timestamptz
        and e.primary_country is not distinct from f.primary_country)
    on conflict (slug) do nothing
    returning 1)
  select count(*) into n_ins from fresh;

  drop table _seg;
  return query select n_ins, n_upd;
end;
$$;

-- ----------------------------------------------------------------------------- records

-- Each record carries the window it was measured over, because they are not the same window.
-- Altitude and speed exist only for the raw fix log; distances by mode only where journeys
-- were imported. A "highest point ever" measured over three weeks of one source, presented
-- next to a "longest trip" measured over four years of another, is a lie of omission.
create or replace view location_v_records as
with raw_window as (
  select min(captured_at) as f, max(captured_at) as l from location_raw_positions
), day_window as (
  select min(day)::timestamptz as f, max(day)::timestamptz as l from location_m_day_home
), highest as (
  select 'highest'::text as kind, 'Highest point'::text as label,
         r.altitude_m::float8 as value, 'm'::text as unit, r.captured_at as at, r.lat, r.lon,
         w.f as covers_from, w.l as covers_to
  from location_raw_positions r cross join raw_window w
  where r.altitude_m is not null and coalesce(r.accuracy_m, 0) < 100
  order by r.altitude_m desc limit 1
), fastest as (
  select 'fastest', 'Fastest', r.speed_ms * 3.6, 'km/h', r.captured_at, r.lat, r.lon, w.f, w.l
  from location_raw_positions r cross join raw_window w
  where r.speed_ms is not null and coalesce(r.accuracy_m, 0) < 100
  order by r.speed_ms desc limit 1
), farthest as (
  select 'farthest', 'Farthest from home', d.km_from_home, 'km', d.day::timestamptz,
         d.anchor_lat, d.anchor_lon, w.f, w.l
  from location_m_day_home d cross join day_window w
  order by d.km_from_home desc nulls last limit 1
), north as (
  select 'north', 'Northernmost', d.anchor_lat, 'N', d.day::timestamptz,
         d.anchor_lat, d.anchor_lon, w.f, w.l
  from location_m_day_home d cross join day_window w
  where d.anchor_lat is not null order by d.anchor_lat desc limit 1
), south as (
  select 'south', 'Southernmost', d.anchor_lat, 'N', d.day::timestamptz,
         d.anchor_lat, d.anchor_lon, w.f, w.l
  from location_m_day_home d cross join day_window w
  where d.anchor_lat is not null order by d.anchor_lat asc limit 1
), east as (
  select 'east', 'Easternmost', d.anchor_lon, 'E', d.day::timestamptz,
         d.anchor_lat, d.anchor_lon, w.f, w.l
  from location_m_day_home d cross join day_window w
  where d.anchor_lon is not null order by d.anchor_lon desc limit 1
), west as (
  select 'west', 'Westernmost', d.anchor_lon, 'E', d.day::timestamptz,
         d.anchor_lat, d.anchor_lon, w.f, w.l
  from location_m_day_home d cross join day_window w
  where d.anchor_lon is not null order by d.anchor_lon asc limit 1
), longest as (
  select 'longest_trip', 'Longest trip', t.nights::float8, 'nights', t.started_at,
         null::float8, null::float8, w.f, w.l
  from location_trips t cross join day_window w
  order by t.nights desc limit 1
), visit_cities as (
  select (v.started_at + make_interval(mins => coalesce(v.start_offset_m, 0)))::date as day, p.city
  from location_visits v
  join location_google_places g on g.place_id = v.google_place_id
  join location_places p on p.id = g.place_id_ref
  where p.city is not null and p.city <> ''
), busiest as (
  select 'busiest_day', 'Most cities in a day', count(distinct c.city)::float8, 'cities',
         c.day::timestamptz, d.anchor_lat, d.anchor_lon, w.f, w.l
  from visit_cities c cross join day_window w
  left join location_m_day_home d on d.day = c.day
  group by c.day, d.anchor_lat, d.anchor_lon, w.f, w.l
  order by count(distinct c.city) desc limit 1
), longest_flight as (
  select 'longest_flight', 'Longest flight', a.distance_m / 1000.0, 'km', a.started_at,
         a.start_lat, a.start_lon,
         (select min(started_at) from location_activities),
         (select max(ended_at) from location_activities)
  from location_activities a where a.mode = 'FLYING'
  order by a.distance_m desc nulls last limit 1
)
select * from highest
union all select * from fastest
union all select * from farthest
union all select * from north
union all select * from south
union all select * from east
union all select * from west
union all select * from longest
union all select * from busiest
union all select * from longest_flight;

commit;
