-- Optional, and part two of the people bridge. Run it only after 0002_people_bridge.sql.
--
-- A trip is something the archive detects: nights far enough from home, for long enough. A
-- weekend at a friend's, an evening, a week at your parents' are none of them trips, and that
-- is where half of "who was I with" actually lives. So this adds the other half of the link:
-- a window you draw yourself, on a person, with times optional.
--
-- Nothing about a place is ever written on the person. You say who and when; where the two of
-- you were is derived from the archive at read time, so it stays true as the archive fills in.
--
-- Idempotent: every object is `create or replace`, `if not exists`, or guarded.
--
--     psql "$LOCATION_DATABASE_URL" -f migrations/0003_companions.sql

begin;

do $$
begin
  if to_regclass('public.people') is null then
    raise exception
      'no `people` table in this database. This migration extends the optional people bridge; '
      'skip it, or install a people graph first. The location schema works without it.';
  end if;
  if to_regclass('public.location_v_trip_people') is null then
    raise exception
      'run migrations/0002_people_bridge.sql first: this file replaces the views it creates.';
  end if;
end $$;

-- ---------------------------------------------------------------- the timezone of a moment
--
-- A day-grained window ("1 to 5 August") is five local days wherever you stood, not five UTC
-- days. Eight hours of difference on both edges is a whole evening of stays landing in the
-- wrong window. The archive already knows which timezone you were in, so nothing has to be
-- typed or guessed: the nearest evidence to the instant wins.
--
-- Two index-backed lookups per direction rather than a scan, because this runs in a trigger
-- and location_pings grows without bound.
create or replace function location_tz_at(t timestamptz)
returns text
language sql stable
set search_path = public as $$
  with before as (
    select at, tz from (
      (select v.started_at as at, nullif(pl.tz, '') as tz
         from location_visits v join location_places pl on pl.id = v.place_id
        where v.started_at <= t and nullif(pl.tz, '') is not null
        order by v.started_at desc limit 1)
      union all
      (select p.captured_at, coalesce(nullif(p.tz, ''), nullif(pl.tz, ''))
         from location_pings p left join location_places pl on pl.id = p.place_id
        where p.captured_at <= t
          and coalesce(nullif(p.tz, ''), nullif(pl.tz, '')) is not null
        order by p.captured_at desc limit 1)
    ) b order by at desc limit 1
  ),
  after as (
    select at, tz from (
      (select v.started_at as at, nullif(pl.tz, '') as tz
         from location_visits v join location_places pl on pl.id = v.place_id
        where v.started_at > t and nullif(pl.tz, '') is not null
        order by v.started_at limit 1)
      union all
      (select p.captured_at, coalesce(nullif(p.tz, ''), nullif(pl.tz, ''))
         from location_pings p left join location_places pl on pl.id = p.place_id
        where p.captured_at > t
          and coalesce(nullif(p.tz, ''), nullif(pl.tz, '')) is not null
        order by p.captured_at limit 1)
    ) a order by at limit 1
  )
  -- whichever piece of evidence sits closest to the instant, and UTC when the archive is
  -- silent on both sides (an empty install, or a window in the far future)
  select coalesce(
    (select tz from (
       select at, tz from before union all select at, tz from after
     ) c order by abs(extract(epoch from (c.at - t))) limit 1),
    'UTC');
$$;

-- ---------------------------------------------------------------- the record

-- No foreign key to `people`, for the same reason 0002 has none: a hard reference would tie
-- the two products' migrations together forever. The join is checked at read time, and a
-- deleted person leaves a window that no view returns.
create table if not exists location_companions (
  id         bigint generated by default as identity primary key,
  person_id  bigint      not null,
  -- half-open, always: [started_at, ended_at). A day window ends at midnight of the day after
  -- the last one, so overlap maths never has to care which grain a row carries.
  started_at timestamptz not null,
  ended_at   timestamptz not null,
  -- false when only dates were given, true when clock times were. Display only: the instants
  -- above are authoritative either way.
  has_time   boolean     not null default false,
  -- the zone the window was read in, stamped at write time so it reads back the same way from
  -- anywhere. Filled by the trigger when the client leaves it empty.
  tz         text        not null default '',
  note       text        not null default '',
  source     text        not null default 'agent',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint location_companions_window check (ended_at > started_at)
);

create index if not exists location_companions_person on location_companions (person_id);
create index if not exists location_companions_window_idx
  on location_companions (started_at, ended_at);

-- The same person cannot be with you twice over the same hours. Without this a double click on
-- an add button is a silent duplicate, and every "days together" number is then wrong.
do $$
begin
  if not exists (select 1 from pg_extension where extname = 'btree_gist') then
    -- Supabase keeps extensions in their own schema; a plain Postgres has no such schema.
    begin
      execute 'create extension btree_gist with schema extensions';
    exception when others then
      begin execute 'create extension btree_gist'; exception when others then null; end;
    end;
  end if;
  if exists (select 1 from pg_extension where extname = 'btree_gist')
     and not exists (select 1 from pg_constraint where conname = 'location_companions_no_overlap')
  then
    execute 'alter table location_companions add constraint location_companions_no_overlap '
         || 'exclude using gist (person_id with =, tstzrange(started_at, ended_at) with &&)';
  end if;
end $$;

-- Wall clock in, instants out.
--
-- One rule decides it: a client that sends `tz` knows what instant it means and is taken
-- literally; a client that leaves `tz` empty is sending wall clock, and the trigger reads that
-- clock in the zone you were standing in. So a browser in Paris posting `2026-07-03` with
-- `18:00` for a day spent in San Francisco records 18:00 in San Francisco, without the browser
-- having to know where you were. PostgREST hands a bare date over as midnight UTC, which is
-- exactly the wall clock a date input types.
--
-- A day window is then snapped to local midnights at both ends, so an evening that runs past
-- midnight cannot silently claim the next day.
create or replace function location_companions_normalize()
returns trigger
language plpgsql
set search_path = public as $$
declare
  d0 date;
  d1 date;
begin
  if coalesce(new.tz, '') = '' then
    new.tz := location_tz_at(new.started_at);
    new.started_at := (new.started_at at time zone 'UTC') at time zone new.tz;
    new.ended_at   := (new.ended_at   at time zone 'UTC') at time zone new.tz;
  end if;
  if not new.has_time then
    d0 := (new.started_at at time zone new.tz)::date;
    d1 := ((new.ended_at - interval '1 second') at time zone new.tz)::date;
    new.started_at := d0::timestamp at time zone new.tz;
    new.ended_at   := (d1 + 1)::timestamp at time zone new.tz;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists location_companions_normalize_t on location_companions;
create trigger location_companions_normalize_t
  before insert or update on location_companions
  for each row execute function location_companions_normalize();

-- ---------------------------------------------------------------- where you were, derived

-- Rebuilt rather than replaced: these four are this file's own, and `create or replace view`
-- refuses a column that moves, so a later version of this file could not ship otherwise.
drop view if exists people_v_together_places;
drop view if exists location_v_companions;
drop view if exists location_v_companion_days;
drop view if exists location_v_companion_stays;

-- One row per (window, stay) overlap: the raw material behind every count below. Reads
-- location_v_stays, the history spine, so it covers imported history and the live tail alike.
create view location_v_companion_stays as
  select c.id as companion_id, c.person_id, p.full_name,
         s.place_id, s.label, s.address, s.city, s.admin, s.country, s.country_code, s.tz,
         s.day, s.trip_id, s.trip_slug, s.trip_name,
         greatest(s.started_at, c.started_at) as started_at,
         least(s.ended_at, c.ended_at)        as ended_at,
         extract(epoch from (least(s.ended_at, c.ended_at)
                             - greatest(s.started_at, c.started_at)))::bigint as seconds
  from location_companions c
  join people p on p.id = c.person_id
  join location_v_stays s
    on s.started_at < c.ended_at and s.ended_at > c.started_at;

-- The same overlap, cut into local days, because "how many days did we spend in Cape Town"
-- cannot be counted on stays: one imported visit can cover nine days in a single row, and
-- counting rows answers 1. The series is bounded by the window, never by the stay.
create view location_v_companion_days as
  select cs.companion_id, cs.person_id, cs.full_name,
         cs.place_id, cs.label, cs.city, cs.admin, cs.country, cs.country_code,
         g.d::date as day,
         extract(epoch from (
           least(cs.ended_at,   ((g.d::date + 1)::timestamp at time zone z.tz))
           - greatest(cs.started_at, (g.d::date::timestamp at time zone z.tz))
         ))::bigint as seconds
  from location_v_companion_stays cs
  cross join lateral (select coalesce(nullif(cs.tz, ''), 'UTC') as tz) z
  cross join lateral generate_series(
    (cs.started_at at time zone z.tz)::date,
    ((cs.ended_at at time zone z.tz) - interval '1 second')::date,
    interval '1 day') g(d);

-- The windows themselves, readable: who, when, and where that lands.
create view location_v_companions as
  select c.id, c.person_id, p.full_name, p.current_org,
         c.started_at, c.ended_at, c.has_time, c.tz, c.note, c.source,
         c.created_at, c.updated_at,
         (c.started_at at time zone c.tz)::date                            as started_on,
         ((c.ended_at at time zone c.tz) - interval '1 second')::date      as ended_on,
         -- a day window of 1 to 5 August is 5 days, not 4: the end is exclusive
         greatest(1, ((c.ended_at at time zone c.tz) - interval '1 second')::date
                     - (c.started_at at time zone c.tz)::date + 1)         as days,
         extract(epoch from (c.ended_at - c.started_at))::bigint           as seconds,
         w.countries, w.cities, w.places, w.days_with_evidence, w.first_day, w.last_day,
         t.trips
  from location_companions c
  join people p on p.id = c.person_id
  left join lateral (
    select array_agg(distinct d.country) filter (where d.country is not null and d.country <> '')
             as countries,
           array_agg(distinct d.city)    filter (where d.city is not null and d.city <> '')
             as cities,
           count(distinct d.place_id)   as places,
           count(distinct d.day)        as days_with_evidence,
           min(d.day)                   as first_day,
           max(d.day)                   as last_day
    from location_v_companion_days d
    where d.companion_id = c.id
  ) w on true
  -- a trip is claimed on the window overlapping the trip, never on the stays inside it: a
  -- visit that starts on the last night of a trip and runs ten days past it belongs to the
  -- trip as far as location_v_stays is concerned, which puts the wrong trip on a home evening
  left join lateral (
    select array_agg(tr.name order by tr.started_at) as trips
    from location_trips tr
    where tr.started_at < c.ended_at and tr.ended_at > c.started_at
  ) t on true;

-- "Where have I been with X", the question the whole bridge exists to answer.
create view people_v_together_places as
  select person_id, full_name, country, country_code, city,
         sum(seconds)::bigint       as seconds,
         count(distinct day)        as days,
         count(distinct place_id)   as places,
         min(day)                   as first_day,
         max(day)                   as last_day
  from location_v_companion_days
  where city is not null and city <> ''
  group by person_id, full_name, country, country_code, city;

-- ---------------------------------------------------------------- the two joins, unified
--
-- A person tagged on a trip and a person whose window covers that trip are the same fact told
-- two ways, so every reader keeps reading one view and a `via` column says which one wrote it.
-- Explicit wins on a tie: it carries the role and note that were typed.
--
-- `via` is appended, never inserted: `create or replace view` refuses anything else, and both
-- the MCP tools and any UI select these columns by name.
create or replace view location_v_trip_people as
  select distinct on (trip_id, person_id)
         trip_id, slug, trip_name, started_at, ended_at,
         person_id, full_name, current_org, job_title, role, note, via
  from (
    select t.id as trip_id, t.slug, t.name as trip_name, t.started_at, t.ended_at,
           p.id as person_id, p.full_name, p.current_org, p."current_role" as job_title,
           tp.role, tp.note, 'trip'::text as via
    from location_trips t
    join location_trip_people tp on tp.trip_id = t.id
    join people p on p.id = tp.person_id
    union all
    select t.id, t.slug, t.name, t.started_at, t.ended_at,
           p.id, p.full_name, p.current_org, p."current_role",
           'with', c.note, 'range'
    from location_trips t
    join location_companions c
      on c.started_at < t.ended_at and c.ended_at > t.started_at
    join people p on p.id = c.person_id
  ) u
  order by trip_id, person_id, (via = 'trip') desc;

create or replace view people_v_trips as
  select person_id, full_name, trip_id, slug, trip_name,
         started_at, ended_at, nights, countries, primary_country, role, note, via
  from (
    select distinct on (tp.person_id, tp.trip_id)
           p.id as person_id, p.full_name, t.id as trip_id, t.slug, t.name as trip_name,
           t.started_at, t.ended_at, t.nights, t.countries, t.primary_country,
           tp.role, tp.note, tp.via
    from location_v_trip_people tp
    join people p on p.id = tp.person_id
    join location_trips t on t.id = tp.trip_id
    order by tp.person_id, tp.trip_id
  ) u;

commit;
